# Aula 02 - Python

## Dados numéricos

In [10]:
# variável inteira
a=1
print("valor de a = "+str(a))
type(a)

valor de a = 1


int

In [11]:
#variavel dupla precisão
b=1.0
print("valor de b = "+str(b))
type(b)

valor de b = 1.0


float

In [12]:
# converter float para int
c=int(b)
print(c)
type(c)

1


int

In [14]:
#Declarando valor nan
import numpy as np
d=np.nan
print(d)
type(d)

nan


float

In [18]:
# multiplicando operação com NaN
e=d*1
print(e)
e=np.nansum([d,1])
print(e)


nan
1.0


## Dados texto

In [22]:
# Declaração de variável texto
f='Fabio'
g="Gabriel"
print(f)
print(g)
print(f+g) #concatenação
print (f+' '+g)

Fabio
Gabriel
FabioGabriel
Fabio Gabriel


## Dados tipo bool - lógica

In [23]:
a==1

True

In [24]:
h=(a==1)
print(h)
type(h)

True


bool

In [25]:
h=(a==2)
print(h)
type(h)

False


bool

In [28]:
i=True
type(i)

bool

In [29]:
ii='True'
type(ii)

str

## Operação de comparação

In [31]:
#Operação igual
a==b

True

In [32]:
#Operação ><
a>b

False

In [33]:
#Operação !=
a!=b

False

In [34]:
#Operação >= ou <=
a<=c

True

## Operações matemáticas

In [35]:
# Soma
a+b

2.0

In [37]:
# multiplicação
j = a*b
print(j)

1.0


In [38]:
# Divisão
a/b

1.0

In [40]:
# Potencia
5**2

25

In [41]:
#operações matematicas com a biblioteva math
import math
math.exp(10)

22026.465794806718

In [42]:
math.exp(a)

2.718281828459045

In [43]:
math.exp(0)


1.0

## Listas

In [44]:
myFirstList=[1,2,3]
print(myFirstList)

[1, 2, 3]


In [48]:
# Assessando pelo index
print(myFirstList[0])

1


In [49]:
myFirstList==a

False

In [51]:
mySecList=[1,a,'c']
print(mySecList)

[1, 1, 'c']


In [52]:
type(mySecList)

list

## Caminhos path

In [54]:
path=r"C:\Users\edinei.acm\ENS410064_OK\ENS410064"
print(path)

C:\Users\edinei.acm\ENS410064_OK\ENS410064


In [56]:
path="C:/Users/edinei.acm/ENS410064_OK/ENS410064"
print(path)

C:/Users/edinei.acm/ENS410064_OK/ENS410064


In [65]:
import os #biblioteca para navegar
#listar arquivos na pasta
os.listdir(path)

['.git', '.gitignore', 'Dados', 'pyEnv', 'README.md', 'Script']

In [66]:
#selecionar primeiro arquivo listado
os.listdir(path)[0]

'.git'

In [67]:
#concatenando caminhos
path+'/'+os.listdir(path)[0]

'C:/Users/edinei.acm/ENS410064_OK/ENS410064/.git'

In [61]:
os.listdir(path+'/'+os.listdir(path)[0])

['config',
 'description',
 'FETCH_HEAD',
 'HEAD',
 'hooks',
 'index',
 'info',
 'logs',
 'objects',
 'packed-refs',
 'refs']

In [68]:
#diretório que estou trabalhando
os.getcwd()

'C:\\Users\\edinei.acm\\ENS410064_OK'

In [69]:
#mudar de diretório
os.chdir('C:\\Users\\edinei.acm\\ENS410064_OK\\')

In [64]:
os.getcwd()

'C:\\Users\\edinei.acm\\ENS410064_OK'

In [76]:
#criando diretório
newPath=os.getcwd()+'/test'
if os.path.isdir(newPath):
    print('Diretório já existe')
else:
    print('Criando diretório '+newPath)
    os.mkdir(newPath)

Diretório já existe


In [82]:
#criando diretório
newPath=os.getcwd()+'/test'
if os.path.isdir(newPath):
    print('Diretório já existe')
    #Criando um arquivo de texto
    with open(newPath+'/copy.text','w') as file:
       file.write('Your text goes here')
else:
    print('Criando diretório '+newPath)
    os.mkdir(newPath)

Diretório já existe


## Numpy arrays e pandas DataFrames

In [85]:
import numpy as np

#criando uma variável numpy
n=np.array(0)
type(n)

numpy.ndarray

In [86]:
#criando uma variável numpy a partir de uma lista
myThirdList=[1,2,3,10,20,55]
n=np.array(myThirdList)
print(n)

[ 1  2  3 10 20 55]


In [91]:
#criando matriz aleatória
n=np.random.rand(10,10)
print(n)
#dimensão da matriz
print('Ordem da matriz é '+str(n.shape))

[[0.08819416 0.33921961 0.03760816 0.9433064  0.33244945 0.17590854
  0.67548183 0.66690392 0.53508004 0.75393089]
 [0.91124928 0.17432718 0.9989521  0.0621848  0.45013448 0.66097209
  0.00521927 0.18461894 0.09473317 0.99129229]
 [0.53885177 0.96573801 0.97047226 0.12472952 0.1251003  0.11652108
  0.56425193 0.00807218 0.35782531 0.09620209]
 [0.28089935 0.70515165 0.40033604 0.65518354 0.82837861 0.68400506
  0.23253442 0.28234174 0.33221271 0.55765923]
 [0.30241254 0.18251296 0.03917974 0.9726239  0.32749122 0.87448401
  0.24084997 0.75725617 0.38778146 0.35418046]
 [0.68730032 0.92061177 0.16483116 0.1561661  0.92913761 0.06816785
  0.32510265 0.1521196  0.50819904 0.29705522]
 [0.75029319 0.26656857 0.85093136 0.64563536 0.70040242 0.39899709
  0.18248278 0.79066425 0.97770257 0.55917949]
 [0.38726521 0.88755773 0.69259964 0.6237476  0.35451895 0.3856988
  0.41477511 0.59591711 0.0841134  0.76985262]
 [0.35922912 0.37094842 0.86328644 0.25355944 0.13674726 0.83632001
  0.33806504 

In [92]:
#acessando valores da matriz
n[0,0]

0.08819415555338628

In [93]:
n[:,1]

array([0.33921961, 0.17432718, 0.96573801, 0.70515165, 0.18251296,
       0.92061177, 0.26656857, 0.88755773, 0.37094842, 0.77666666])

In [95]:
# da coluna 1 até a 5, ou seja, colunas 1, 2, 3 e 4
n[:,1:5]

array([[0.33921961, 0.03760816, 0.9433064 , 0.33244945],
       [0.17432718, 0.9989521 , 0.0621848 , 0.45013448],
       [0.96573801, 0.97047226, 0.12472952, 0.1251003 ],
       [0.70515165, 0.40033604, 0.65518354, 0.82837861],
       [0.18251296, 0.03917974, 0.9726239 , 0.32749122],
       [0.92061177, 0.16483116, 0.1561661 , 0.92913761],
       [0.26656857, 0.85093136, 0.64563536, 0.70040242],
       [0.88755773, 0.69259964, 0.6237476 , 0.35451895],
       [0.37094842, 0.86328644, 0.25355944, 0.13674726],
       [0.77666666, 0.51287432, 0.67041337, 0.84125736]])

In [96]:
# primeira linha, da coluna 4 até a ultima (não considera a ultima)
n[0,4:-1]

array([0.33244945, 0.17590854, 0.67548183, 0.66690392, 0.53508004])

In [97]:
# primeria linha, da coluna 4 até o fim
n[0,4:]

array([0.33244945, 0.17590854, 0.67548183, 0.66690392, 0.53508004,
       0.75393089])

In [98]:
an=np.log(n*5)

In [99]:
print(an)

[[-0.81877667  0.52833034 -1.67109628  1.55107379  0.50817045 -0.12835316
   1.2171089   1.20432862  0.98409898  1.32698334]
 [ 1.51649913 -0.13738351  1.60838947 -1.1682068   0.81122902  1.19539424
  -3.64595931 -0.08002344 -0.7472532   1.60069207]
 [ 0.99112317  1.57457522  1.57946545 -0.4721698  -0.46920158 -0.54024519
   1.03718347 -3.20989327  0.58172755 -0.73186628]
 [ 0.33967906  1.26009552  0.69398693  1.18659805  1.42115294  1.22964794
   0.15072087  0.34480081  0.5074581   1.02543071]
 [ 0.41347474 -0.09149617 -1.63015753  1.5816801   0.49314387  1.47531664
   0.18585684  1.33138424  0.66212456  0.57148919]
 [ 1.23445398  1.52672105 -0.19339568 -0.24739719  1.53593949 -1.07634439
   0.4858236  -0.27365034  0.93255582  0.39560068]
 [ 1.32214668  0.28731415  1.4480141   1.17191752  1.25333769  0.69063676
  -0.09166153  1.37455604  1.58688814  1.02815315]
 [ 0.66079238  1.4901562   1.24213475  1.13742843  0.57244443  0.65673939
   0.7294191   1.09178421 -0.86615144  1.34788172]
